import { Innertube } from "youtubei.js";

export class TranscriptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TranscriptError";
  }
}

export interface TranscriptSegmentRaw {
  start_seconds: number;
  duration_seconds: number;
  text: string;
}

export interface TranscriptResult {
  segments: TranscriptSegmentRaw[];
  language: string;
  isAutoGenerated: boolean;
  availableLanguages: string[];
}

// Best-effort ISO 639-1 -> English display name lookup, used by the transcript-panel
// fallback to match a requested `language` against the human-readable track names
// youtubei.js exposes (e.g. "Portuguese (auto-generated)"). The Innertube session is
// created with lang: "en" so these names are always in English.
const LANGUAGE_NAMES: Record<string, string> = {
  pt: "portuguese",
  en: "english",
  es: "spanish",
  fr: "french",
  de: "german",
  it: "italian",
  ja: "japanese",
  ko: "korean",
  zh: "chinese",
  ru: "russian",
  ar: "arabic",
  hi: "hindi",
  nl: "dutch",
  pl: "polish",
  tr: "turkish",
  id: "indonesian",
  th: "thai",
  vi: "vietnamese",
  sv: "swedish",
  no: "norwegian",
  da: "danish",
  fi: "finnish",
  el: "greek",
  he: "hebrew",
  uk: "ukrainian",
  cs: "czech",
  ro: "romanian",
  hu: "hungarian",
};

let innertubePromise: Promise<Innertube> | null = null;

function getInnertube(): Promise<Innertube> {
  if (!innertubePromise) {
    innertubePromise = Innertube.create({ lang: "en", retrieve_player: false });
  }
  return innertubePromise;
}

function isAutoGeneratedLabel(label: string): boolean {
  return label.toLowerCase().includes("auto-generated");
}

function decodeXmlEntities(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

// The timedtext endpoint rate-limits bursts (intermittent 429 "Sorry..." pages), so
// downloads are serialized through this chain with a small gap between requests
// instead of firing in parallel for batch tool calls.
let timedtextQueue: Promise<unknown> = Promise.resolve();
const TIMEDTEXT_GAP_MS = 800;

function enqueueTimedtext<T>(task: () => Promise<T>): Promise<T> {
  const result = timedtextQueue.then(task);
  timedtextQueue = result
    .catch(() => undefined)
    .then(() => new Promise((resolve) => setTimeout(resolve, TIMEDTEXT_GAP_MS)));
  return result;
}

/** Fetch a timedtext URL, retrying the intermittent 429 ("Sorry...") rate-limit responses. */
function fetchTimedtextBody(url: string): Promise<string> {
  return enqueueTimedtext(async () => {
    const delaysMs = [0, 3000, 8000];
    let lastFailure = "";
    for (const delay of delaysMs) {
      if (delay > 0) await new Promise((resolve) => setTimeout(resolve, delay + Math.random() * 1000));
      const response = await fetch(url);
      const body = await response.text();
      if (response.status === 200 && body.trim().length > 0) return body;
      lastFailure = response.status === 200 ? "empty response body" : `HTTP ${response.status}`;
    }
    throw new TranscriptError(`Caption download failed after retries (${lastFailure}) — likely YouTube rate limiting.`);
  });
}

/** Parse caption data in either srv3 XML (<timedtext format="3">) or json3 format. */
function parseCaptionBody(body: string): TranscriptSegmentRaw[] {
  const segments: TranscriptSegmentRaw[] = [];
  const trimmed = body.trim();

  if (trimmed.startsWith("{")) {
    const data = JSON.parse(trimmed) as {
      events?: { tStartMs?: number; dDurationMs?: number; segs?: { utf8?: string }[] }[];
    };
    for (const event of data.events ?? []) {
      if (!event.segs) continue;
      const text = event.segs
        .map((s) => s.utf8 ?? "")
        .join("")
        .replace(/\s+/g, " ")
        .trim();
      if (!text) continue;
      segments.push({
        start_seconds: (event.tStartMs ?? 0) / 1000,
        duration_seconds: (event.dDurationMs ?? 0) / 1000,
        text,
      });
    }
    return segments;
  }

  for (const match of trimmed.matchAll(/<p\b([^>]*)>([\s\S]*?)<\/p>/g)) {
    const attrs = match[1];
    const text = decodeXmlEntities(match[2].replace(/<[^>]+>/g, " "))
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;
    const startMs = Number(/\bt="(\d+)"/.exec(attrs)?.[1] ?? 0);
    const durationMs = Number(/\bd="(\d+)"/.exec(attrs)?.[1] ?? 0);
    segments.push({
      start_seconds: startMs / 1000,
      duration_seconds: durationMs / 1000,
      text,
    });
  }
  return segments;
}

interface CaptionTrackInfo {
  base_url: string;
  language_code: string;
  kind?: string;
  name?: { toString(): string };
}

/**
 * Primary route: caption tracks from the ANDROID-client player response, downloaded
 * via YouTube's timedtext endpoint. The WEB player response omits caption tracks
 * without a PoToken, and the WEB "get_transcript" panel endpoint has returned
 * intermittent 400 FAILED_PRECONDITION since Dec 2025 (LuanRT/YouTube.js#1102);
 * the ANDROID client still serves full caption metadata with working URLs.
 */
async function fetchViaCaptionTracks(videoId: string, preferredLanguage?: string): Promise<TranscriptResult> {
  const youtube = await getInnertube();

  let tracks: CaptionTrackInfo[];
  let defaultTrackIndex: number | undefined;
  try {
    const info = await youtube.getBasicInfo(videoId, { client: "ANDROID" });
    tracks = (info.captions?.caption_tracks ?? []) as CaptionTrackInfo[];
    const audioTracks = info.captions?.audio_tracks;
    const defaultAudioTrack = audioTracks?.[info.captions?.default_audio_track_index ?? 0] ?? audioTracks?.[0];
    defaultTrackIndex = defaultAudioTrack?.default_caption_track_index;
  } catch (error) {
    throw new TranscriptError(`Could not load video info: ${error instanceof Error ? error.message : String(error)}`);
  }

  if (tracks.length === 0) {
    throw new TranscriptError(
      "This video has no caption tracks (it may have no captions, be a livestream, or have captions disabled).",
    );
  }

  let track: CaptionTrackInfo | undefined;
  if (preferredLanguage) {
    const wanted = preferredLanguage.toLowerCase();
    track =
      tracks.find((t) => t.language_code?.toLowerCase() === wanted) ??
      tracks.find((t) => t.language_code?.toLowerCase().startsWith(`${wanted}-`));
  }
  // No preference or no match: use YouTube's own default caption track for the
  // default audio track (tracks are listed alphabetically, so "first" is wrong),
  // falling back to the first manually-created track over auto-generated ("asr").
  if (!track) {
    track =
      (defaultTrackIndex !== undefined ? tracks[defaultTrackIndex] : undefined) ??
      tracks.find((t) => t.kind !== "asr") ??
      tracks[0];
  }

  const body = await fetchTimedtextBody(`${track.base_url}&fmt=json3`);
  const segments = parseCaptionBody(body);
  if (segments.length === 0) {
    throw new TranscriptError(
      "The caption track downloaded but contained no text segments (this can happen for a video with an empty or " +
        "non-text-based caption track).",
    );
  }

  const label = track.name?.toString() || track.language_code || "unknown";
  return {
    segments,
    language: label,
    isAutoGenerated: track.kind === "asr" || isAutoGeneratedLabel(label),
    availableLanguages: tracks.map((t) => t.name?.toString() || t.language_code).filter(Boolean),
  };
}

/** Fallback route: the "Show transcript" panel, same mechanism as the youtube.com button. */
async function fetchViaTranscriptPanel(videoId: string, preferredLanguage?: string): Promise<TranscriptResult> {
  const youtube = await getInnertube();

  let info;
  try {
    info = await youtube.getInfo(videoId);
  } catch (error) {
    throw new TranscriptError(`Could not load video info: ${error instanceof Error ? error.message : String(error)}`);
  }

  let transcriptInfo;
  try {
    transcriptInfo = await info.getTranscript();
  } catch (error) {
    throw new TranscriptError(
      `No transcript panel is available for this video (it may have no captions, be a livestream, or have transcripts disabled): ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const availableLanguages = transcriptInfo.languages;

  if (preferredLanguage) {
    const wantedName = LANGUAGE_NAMES[preferredLanguage.toLowerCase()];
    const match = wantedName ? availableLanguages.find((l) => l.toLowerCase().includes(wantedName)) : undefined;
    if (match && match !== transcriptInfo.selectedLanguage) {
      try {
        transcriptInfo = await transcriptInfo.selectLanguage(match);
      } catch {
        // Fall through and use whatever language was already selected.
      }
    }
  }

  const initialSegments = transcriptInfo.transcript.content?.body?.initial_segments ?? [];
  const segments: TranscriptSegmentRaw[] = [];
  for (const segment of initialSegments) {
    const text = segment.snippet?.toString().replace(/\s+/g, " ").trim();
    if (!text) continue;
    const startMs = Number(segment.start_ms ?? 0);
    const endMs = Number(segment.end_ms ?? 0);
    segments.push({
      start_seconds: startMs / 1000,
      duration_seconds: Math.max(0, (endMs - startMs) / 1000),
      text,
    });
  }

  if (segments.length === 0) {
    throw new TranscriptError(
      "The transcript panel loaded but contained no text segments (this can happen for a video with an empty or " +
        "non-text-based caption track).",
    );
  }

  const selectedLanguage = transcriptInfo.selectedLanguage || availableLanguages[0] || "unknown";

  return {
    segments,
    language: selectedLanguage,
    isAutoGenerated: isAutoGeneratedLabel(selectedLanguage),
    availableLanguages,
  };
}

export async function fetchTranscript(videoId: string, preferredLanguage?: string): Promise<TranscriptResult> {
  let primaryError: TranscriptError;
  try {
    return await fetchViaCaptionTracks(videoId, preferredLanguage);
  } catch (error) {
    primaryError = error instanceof TranscriptError ? error : new TranscriptError(String(error));
  }

  try {
    return await fetchViaTranscriptPanel(videoId, preferredLanguage);
  } catch (fallbackError) {
    const fallbackMessage = fallbackError instanceof Error ? fallbackError.message : String(fallbackError);
    throw new TranscriptError(`${primaryError.message} (transcript-panel fallback also failed: ${fallbackMessage})`);
  }
}
