import axios from "axios";

const WATCH_URL = "https://www.youtube.com/watch";

// Sends a pre-accepted consent cookie so the request gets the real watch page instead of the
// EU cookie-consent interstitial, which has no caption data.
const CONSENT_COOKIE = "CONSENT=YES+cb.20210328-17-p0.en+FX+100";

const BROWSER_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

export class TranscriptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TranscriptError";
  }
}

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string; // "asr" marks an auto-generated track
  name?: { simpleText?: string } | string;
}

export interface TranscriptSegmentRaw {
  start_seconds: number;
  duration_seconds: number;
  text: string;
}

/**
 * Extracts a JSON array embedded in a larger (non-JSON) string, e.g. `"captionTracks":[...]`
 * inside the ytInitialPlayerResponse blob on a YouTube watch page. Walks brackets manually
 * (respecting quoted strings) instead of using a greedy regex, since caption track objects can
 * contain arbitrary nested content.
 */
function extractJsonArray(source: string, key: string): unknown[] | null {
  const marker = `"${key}":`;
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) return null;
  const arrayStart = source.indexOf("[", markerIndex + marker.length);
  if (arrayStart === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = arrayStart; i < source.length; i++) {
    const ch = source[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(source.slice(arrayStart, i + 1)) as unknown[];
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

export async function getCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  let html: string;
  try {
    const response = await axios.get<string>(WATCH_URL, {
      params: { v: videoId, hl: "en" },
      headers: {
        "Accept-Language": "en-US,en;q=0.9",
        Cookie: CONSENT_COOKIE,
        "User-Agent": BROWSER_USER_AGENT,
      },
      timeout: 15000,
    });
    html = response.data;
  } catch (error) {
    throw new TranscriptError(
      `Could not load the YouTube watch page: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const tracks = extractJsonArray(html, "captionTracks");
  if (!tracks) return [];
  return tracks as CaptionTrack[];
}

function decodeXmlEntities(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_match, code: string) => String.fromCharCode(Number(code)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

export async function fetchTranscriptSegments(track: CaptionTrack): Promise<TranscriptSegmentRaw[]> {
  const baseUrl = track.baseUrl.startsWith("//") ? `https:${track.baseUrl}` : track.baseUrl;

  let xml: string;
  try {
    const response = await axios.get<string>(baseUrl, {
      timeout: 15000,
      headers: { "User-Agent": BROWSER_USER_AGENT },
    });
    xml = response.data;
  } catch (error) {
    throw new TranscriptError(`Could not download the caption track: ${error instanceof Error ? error.message : String(error)}`);
  }

  const segments: TranscriptSegmentRaw[] = [];
  const textTagRe = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  const attrRe = /(\w+)="([^"]*)"/g;
  let match: RegExpExecArray | null;
  while ((match = textTagRe.exec(xml)) !== null) {
    const attrs: Record<string, string> = {};
    attrRe.lastIndex = 0;
    let attrMatch: RegExpExecArray | null;
    while ((attrMatch = attrRe.exec(match[1])) !== null) {
      attrs[attrMatch[1]] = attrMatch[2];
    }
    const text = decodeXmlEntities(match[2].replace(/<[^>]*>/g, "")).replace(/\s+/g, " ").trim();
    if (!text) continue;
    segments.push({
      start_seconds: Number(attrs.start ?? 0),
      duration_seconds: Number(attrs.dur ?? 0),
      text,
    });
  }
  return segments;
}

export function pickBestTrack(tracks: CaptionTrack[], preferredLanguage?: string): CaptionTrack | null {
  if (tracks.length === 0) return null;
  const isAutoGenerated = (t: CaptionTrack) => t.kind === "asr";

  if (preferredLanguage) {
    const lang = preferredLanguage.toLowerCase();
    const matches = tracks.filter((t) => t.languageCode.toLowerCase().startsWith(lang));
    if (matches.length > 0) {
      return matches.find((t) => !isAutoGenerated(t)) ?? matches[0];
    }
  }

  return tracks.find((t) => !isAutoGenerated(t)) ?? tracks[0];
}
