import { Innertube } from "youtubei.js";

export class TranscriptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TranscriptError";
  }
}

export interface TranscriptSegmentRaw {
  start_seconds: number;
  duration_seconds: number;
  text: string;
}

export interface TranscriptResult {
  segments: TranscriptSegmentRaw[];
  language: string;
  isAutoGenerated: boolean;
  availableLanguages: string[];
}

// Best-effort ISO 639-1 -> English display name lookup, used to match a requested `language`
// against the human-readable track names youtubei.js exposes (e.g. "Portuguese (auto-generated)").
// The Innertube session is created with lang: "en" so these names are always in English.
const LANGUAGE_NAMES: Record<string, string> = {
  pt: "portuguese",
  en: "english",
  es: "spanish",
  fr: "french",
  de: "german",
  it: "italian",
  ja: "japanese",
  ko: "korean",
  zh: "chinese",
  ru: "russian",
  ar: "arabic",
  hi: "hindi",
  nl: "dutch",
  pl: "polish",
  tr: "turkish",
  id: "indonesian",
  th: "thai",
  vi: "vietnamese",
  sv: "swedish",
  no: "norwegian",
  da: "danish",
  fi: "finnish",
  el: "greek",
  he: "hebrew",
  uk: "ukrainian",
  cs: "czech",
  ro: "romanian",
  hu: "hungarian",
};

let innertubePromise: Promise<Innertube> | null = null;

function getInnertube(): Promise<Innertube> {
  if (!innertubePromise) {
    innertubePromise = Innertube.create({ lang: "en", retrieve_player: false });
  }
  return innertubePromise;
}

function isAutoGeneratedLabel(label: string): boolean {
  return label.toLowerCase().includes("auto-generated");
}

export async function fetchTranscript(videoId: string, preferredLanguage?: string): Promise<TranscriptResult> {
  const youtube = await getInnertube();

  let info;
  try {
    info = await youtube.getInfo(videoId);
  } catch (error) {
    throw new TranscriptError(`Could not load video info: ${error instanceof Error ? error.message : String(error)}`);
  }

  let transcriptInfo;
  try {
    transcriptInfo = await info.getTranscript();
  } catch (error) {
    throw new TranscriptError(
      `No transcript panel is available for this video (it may have no captions, be a livestream, or have transcripts disabled): ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const availableLanguages = transcriptInfo.languages;

  if (preferredLanguage) {
    const wantedName = LANGUAGE_NAMES[preferredLanguage.toLowerCase()];
    const match = wantedName ? availableLanguages.find((l) => l.toLowerCase().includes(wantedName)) : undefined;
    if (match && match !== transcriptInfo.selectedLanguage) {
      try {
        transcriptInfo = await transcriptInfo.selectLanguage(match);
      } catch {
        // Fall through and use whatever language was already selected.
      }
    }
  }

  const initialSegments = transcriptInfo.transcript.content?.body?.initial_segments ?? [];
  const segments: TranscriptSegmentRaw[] = [];
  for (const segment of initialSegments) {
    const text = segment.snippet?.toString().replace(/\s+/g, " ").trim();
    if (!text) continue;
    const startMs = Number(segment.start_ms ?? 0);
    const endMs = Number(segment.end_ms ?? 0);
    segments.push({
      start_seconds: startMs / 1000,
      duration_seconds: Math.max(0, (endMs - startMs) / 1000),
      text,
    });
  }

  if (segments.length === 0) {
    throw new TranscriptError(
      "The transcript panel loaded but contained no text segments (this can happen for a video with an empty or " +
        "non-text-based caption track).",
    );
  }

  const selectedLanguage = transcriptInfo.selectedLanguage || availableLanguages[0] || "unknown";

  return {
    segments,
    language: selectedLanguage,
    isAutoGenerated: isAutoGeneratedLabel(selectedLanguage),
    availableLanguages,
  };
}
